import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MARKETPLACE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header className={'p-[16px] flex justify-between bg-[#282828] shadow-lg'}>
      <nav style={{ display: 'flex', justifyContent: 'center', gap: 16, fontWeight: 500 }}>
        <Link href={'/'}>Main</Link>
        <Link href={'/cart'}>Cart</Link>
      </nav>
      <Link href={'/admin'}>Admin</Link>
    </header>

    {children}
    </body>
    </html>
  );
}
